alias: 'Toilet movement'
trigger:
  - platform: state
    entity_id: binary_sensor.toilet_motion_sensor_occupancy
    from: 'off'
    to: 'on'
action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.toilet_last_movement
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
  - choose:
      - conditions:
          - condition: time
            before: '08:00:00'
            after: '20:00:00'
        sequence:
          - service: mqtt.publish
            data:
              topic: zigbee2mqtt/Toilet/set
              payload: '{"brightness":120,"color_temp":400,"state":"ON"}'
    default:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Toilet/set
          payload: '{"brightness":255,"color_temp":50,"state":"ON"}'
