alias: 'Toilet no movement'
trigger:
  - platform: state
    entity_id: binary_sensor.toilet_motion_sensor_occupancy
    from: 'on'
    to: 'off'
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Toilet/set/state
      payload: 'OFF'
