config:
frontend:
mobile_app:
sun:
system_health:
updater:
input_datetime:
  attic_last_movement:
    name: Attic last movement detected
    has_date: true
    has_time: true
  bathroom_last_movement:
    name: Bathroom last movement detected
    has_date: true
    has_time: true
  hall_downstairs_last_movement:
    name: Hall downstairs last movement detected
    has_date: true
    has_time: true
  hall_upstairs_last_movement:
    name: Hall upstairs last movement detected
    has_date: true
    has_time: true
  kitchen_last_movement:
    name: Kitchen last movement detected
    has_date: true
    has_time: true
  toilet_last_movement:
    name: Toilet last movement detected
    has_date: true
    has_time: true
input_select:

homeassistant:
  name: Woensel
  external_url: !secret homeassistant_external_url
  internal_url: http://192.168.1.107:8123
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

logger:
  default: info
  logs:
    homeassistant.components.rfxtrx: info
    custom_components.shelly: info

alarm_control_panel:
  - platform: manual

automation: !include automations.yaml
automation mine: !include_dir_list automations/
binary_sensor mine: !include_dir_list binary_sensors/
device_tracker: !include device_trackers.yaml
history: !include history.yaml
logbook: !include logbook.yaml
person: !include persons.yaml
sensor: !include sensors.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 192.168.2.0/24
  server_port: 80

recorder:
  db_url: !secret recorder_db_url

media_player:
webostv:
  host: 192.168.1.192
  name: TV
  customize:
    sources:
      - spotify
      - hdmi1
      - hdmi2
      - hdmi3
      - hdmi4
      - youtube
      - netflix

rfxtrx:
  device: /dev/ttyUSB1
  automatic_add: false
  devices:
    09130002177a0a01ca60:
      device_class: opening
      data_bits: 4
      command_on: 0xa
      command_off: 0xe

mqtt:
  broker: mqtt
  port: 1883
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml

lovelace:
  mode: yaml

switch:
  - platform: mqtt
    icon: mdi:lightbulb-group
    unique_id: bathroom_lights
    name: "Bathroom lights"
    state_topic: "shellies/shelly1-E09806967AEC/relay/0"
    command_topic: "shellies/shelly1-E09806967AEC/relay/0/command"
    payload_off: "off"
    payload_on: "on"
    retain: true
  - platform: mqtt
    icon: mdi:fan
    unique_id: bathroom_fan
    name: "Bathroom fan"
    state_topic: "shellies/shelly1-E09806965DEB/relay/0"
    command_topic: "shellies/shelly1-E09806965DEB/relay/0/command"
    payload_off: "off"
    payload_on: "on"
  - platform: mqtt
    icon: mdi:lightbulb-group
    name: "Christmas tree"
    state_topic: "shellies/shellyplug-s-978063/relay/0"
    command_topic: "shellies/shellyplug-s-978063/relay/0/command"
    payload_off: "off"
    payload_on: "on"

cover:
  - platform: mqtt
    name: "Living room garden cover"
    unique_id: "living_room_garden_cover"
    command_topic: "shellies/shellyswitch25-40F520230E53/roller/0/command"
    position_topic: "shellies/shellyswitch25-40F520230E53/roller/0/pos"
    set_position_topic: "shellies/shellyswitch25-40F520230E53/roller/0/command/pos"
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    retain: true
