- platform: template
  sensors:
    attic_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.attic_last_movement.state }}
    bathroom_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.bathroom_last_movement.state }}
    hall_downstairs_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.hall_downstairs_last_movement.state }}
    hall_upstairs_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.hall_upstairs_last_movement.state }}
    kitchen_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.kitchen_last_movement.state }}
    toilet_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.toilet_last_movement.state }}
    attic_sensor_battery_level:
      friendly_name: Attic sensor battery level
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {{ states.binary_sensor.attic_sensor_1_motion.attributes.battery_level }}
    hall_downstairs_sensor_battery_level:
      friendly_name: Hall downstairs sensor battery level
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {{ states.binary_sensor.hall_downstairs_sensor_motion.attributes.battery_level }}
    hall_upstairs_sensor_battery_level:
      friendly_name: Hall upstairs sensor battery level
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {{ states.binary_sensor.hall_upstairs_sensor_motion.attributes.battery_level }}
    kitchen_sensor_battery_level:
      friendly_name: Kitchen sensor battery level
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {{ states.binary_sensor.kitchen_sensor_motion.attributes.battery_level }}
    toilet_sensor_battery_level:
      friendly_name: Toilet sensor battery level
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {{ states.binary_sensor.toilet_sensor_motion.attributes.battery_level }}
