- platform: template
  sensors:
    attic_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.attic_last_movement.state }}
    bathroom_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.bathroom_last_movement.state }}
    hall_downstairs_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.hall_downstairs_last_movement.state }}
    hall_upstairs_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.hall_upstairs_last_movement.state }}
    kitchen_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.kitchen_last_movement.state }}
    toilet_last_movement:
      device_class: timestamp
      value_template: >-
        {{ states.input_datetime.toilet_last_movement.state }}
- platform: mqtt
  name: "PC Power"
  state_topic: "shellies/shellyplug-s-9A3135/relay/0/power"
  unit_of_measurement: 'Watt'
