title: Woensel
views:
  - title: Overview
    panel: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: weather-forecast
                entity: weather.home
              - type: alarm-panel
                states:
                  - arm_home
                  - arm_away
                entity: alarm_control_panel.ha_alarm
                name: Security
              - type: entities
                entities:
                  - entity: person.rene
                  - entity: person.elle
                state_color: false
                show_header_toggle: false
          - type: horizontal-stack
            cards:
              - type: entities
                title: Living room
                entities:
                  - entity: light.tv_1_light
                  - entity: light.tv_2_light
                  - entity: light.living_room_corner_light
                  - entity: light.dressoir_light
                  - entity: light.living_room_radiator_light
                  - entity: light.dining_1_light
                  - entity: light.dining_2_light
                  - entity: light.dining_3_light
                  - entity: light.living_room_open_closet_light
                  - entity: light.living_room_closet_light
              - type: vertical-stack
                cards:
                  - type: entity
                    entity: media_player.tv
                  - type: entity
                    entity: cover.living_room_garden_cover
                    name: Roller shutter
                  - type: button
                    tap_action:
                      action: toggle
                    entity: switch.christmas_tree
                    show_name: true
                    show_state: false
                    show_icon: true
