title: Woensel
views:
  - title: Overview
    panel: false
    badges:
      - entity: person.rene
      - entity: person.elle
      - entity: alarm_control_panel.ha_alarm
    cards:
      - type: thermostat
        entity: climate.woonkamer
      - type: weather-forecast
        entity: weather.home
      - type: entity
        entity: media_player.tv
      - type: entities
        title: Living room
        entities:
          - entity: group.tv
          - entity: group.dining
          - entity: light.living_room_corner_light
            name: Corner
          - entity: light.living_room_open_closet_light
            name: Open closet
          - entity: light.dressoir_light
            name: Dressoir
          - entity: light.living_room_radiator_light
            name: Radiator
          - entity: light.living_room_closet_light
            name: Closet
      - type: entities
        title: Study
        entities:
#          - entity: climate.studeerkamer
          - entity: binary_sensor.pc
          - entity: light.pc_1_light
          - entity: light.pc_2_light
      - type: entities
        entities:
          - entity: light.master_bedroom_light
      - type: vertical-stack
        title: Covers
        cards:
          - type: entity
            entity: cover.living_room_garden_cover
            name: Garden
          - type: entity
            entity: cover.fibaro_system_fgrm223_roller_shutter_controller_3_level
            name: Master bedroom
          - type: entity
            entity: cover.study_cover
            name: Study
  - title: All
    cards:
      - type: entities
        title: Switches
        entities:
          - entity: light.attic_1_light
          - entity: light.attic_2_light
          - entity: light.dining_1_light
          - entity: light.dining_2_light
          - entity: light.dining_3_light
          - entity: light.dressoir_light
          - entity: light.hall_downstairs_1_light
          - entity: light.hall_downstairs_2_light
          - entity: light.hall_upstairs_1_light
          - entity: light.hall_upstairs_2_light
          - entity: light.kitchen_1_light
          - entity: light.kitchen_2_light
          - entity: light.kitchen_3_light
          - entity: light.kitchen_4_light
          - entity: light.living_room_closet_light
          - entity: light.living_room_corner_light
          - entity: light.living_room_open_closet_light
          - entity: light.living_room_radiator_light
          - entity: light.master_bedroom_light
          - entity: light.pc_1_light
          - entity: light.pc_2_light
          - entity: light.shed_light
          - entity: light.toilet_light
          - entity: light.tv_1_light
          - entity: light.tv_1_light
          - entity: light.tv_2_light
          - entity: switch.bathroom_lights
      - type: entities
        title: Covers
        entities:
          - cover.fibaro_system_fgrm223_roller_shutter_controller_3_level
          - cover.living_room_garden_cover
      - type: entities
        title: Groups
        entities:
          - group.dining
          - group.kitchen
          - group.tv
