alias: 'Front door open'
trigger:
  - platform: state
    entity_id: binary_sensor.pt2262_177a0a
    from: 'off'
    to: 'on'
action:
  - service: 'light.turn_on'
    data_template:
      entity_id:
        - light.hall_downstairs_1_light
        - light.hall_downstairs_2_light
      brightness_pct: >
        {%- if states('sensor.hall_downstairs_sensor_illuminance_lux') | float > 10 -%}
          0.0
        {%- else %}
          {%- if now().hour < 8 or now().hour > 21 -%}
            30
          {%- else -%}
            80
          {%- endif -%}
        {%- endif -%}
