alias: 'Front door security'
trigger:
  - platform: state
    entity_id: binary_sensor.pt2262_177a0a
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.security
    state: 'on'
action:
  - service: notify.mobile_app_skeepaars
    data:
      message: Front door opened while security was enabled
  - service: notify.mobile_app_iphone_van_elle
    data:
      message: Front door opened while security was enabled
