alias: 'Hall downstairs movement or door opened'
trigger:
  - platform: state
    entity_id: binary_sensor.hall_downstairs_sensor_occupancy
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.pt2262_177a0a
    from: 'off'
    to: 'on'
action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.hall_downstairs_last_movement
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.hall_downstairs_sensor_illuminance_lux
            below: '12'
        sequence:
          - choose:
              - conditions:
                  - condition: time
                    before: '10:00:00'
                    after: '17:00:00'
                sequence:
                  - service: mqtt.publish
                    data:
                      topic: zigbee2mqtt/hall_downstairs/set
                      payload: '{"brightness":100,"color_temp":400,"state":"ON"}'
            default:
              - service: mqtt.publish
                data:
                  topic: zigbee2mqtt/hall_downstairs/set
                  payload: '{"brightness":255,"color_temp":100,"state":"ON"}'
