alias: Living room switch button 3
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Living room switch/action
    payload: recall_scene_1
action:
  - service: light.toggle
    entity_id: group.living_room_dining
    data:
      brightness_pct: 50
