alias: Living room switch button 2
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Living room switch/action
    payload: recall_scene_0
action:
  - service: light.toggle
    entity_id:
      - group.living_room_tv
      - light.living_room_corner_light
