alias: Living room switch button 3
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Living room switch/action
    payload: recall_scene_1
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/living_room_dining/set/state
      payload: 'ON'
