alias: Living room switch button 1
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Living room switch/action
    payload: toggle
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/living_room/set/state
      payload: 'OFF'



