alias: Living room switch button 2
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Living room switch/action
    payload: recall_scene_0
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Living room corner/set/state
      payload: 'ON'
