alias: Living room switch button 1
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Living room switch/action
    payload: toggle
action:
#  - service: light.turn_off
#    entity_id: group.living_room
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/living_room/set/state
      payload: 'OFF'



