alias: Televisie uit
trigger:
  - platform: state
    entity_id: media_player.tv
    from: 'on'
    to: 'off'
    for: '30'
action:
  - type: turn_off
    device_id: light.living_room_corner_light
    entity_id: light.living_room_corner_light
    domain: light
