alias: Master bedroom wall button 1
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Master bedroom dimmer switch wall/action
    payload: on-press
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Master bedroom/set
      payload: '{"brightness":255,"color_temp":400,"state":"ON"}'

