alias: Master bedroom wall button 1 hold
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Master bedroom dimmer switch wall/action
    payload: on-hold
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Master bedroom/set
      payload: '{"brightness":255,"color_temp":400,"state":"ON"}'
