alias: Master bedroom wall button 1
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Master bedroom dimmer switch wall/action
    payload: on-press
action:
  - type: turn_on
    device_id: light.master_bedroom_light
    entity_id: light.master_bedroom_light
    domain: light
    brightness_pct: 50
