alias: 'Hall upstairs movement'
trigger:
  - platform: state
    entity_id: binary_sensor.hall_upstairs_sensor_occupancy
    from: 'off'
    to: 'on'
action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.hall_upstairs_last_movement
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.hall_upstairs_sensor_illuminance_lux
            below: '10'
        sequence:
          - choose:
              - conditions:
                  - condition: time
                    before: '08:00:00'
                    after: '20:00:00'
                sequence:
                  - service: mqtt.publish
                    data:
                      topic: zigbee2mqtt/hall_upstairs/set
                      payload: '{"brightness":50,"color_temp":400,"state":"ON"}'
            default:
              - service: mqtt.publish
                data:
                  topic: zigbee2mqtt/hall_upstairs/set
                  payload: '{"brightness":255,"color_temp":50,"state":"ON"}'
