alias: 'Person Elle home'
trigger:
  - platform: state
    entity_id: person.elle
    from: 'not_home'
    to: 'home'
condition:
  - condition: state
    entity_id: input_boolean.security
    state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.security
  - service: notify.mobile_app_skeepaars
    data:
      title: Elle home
      message: Elle has arrived home, security has been disabled
      data:
        push:
          sound: "US-EN-Morgan-Freeman-Girlfriend-Is-Arriving.wav"

