alias: 'Person Rene home'
trigger:
  - platform: state
    entity_id: person.rene
    from: 'not_home'
    to: 'home'
condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: 'armed_away'
action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.ha_alarm
  - service: notify.mobile_app_iphone_van_elle
    data:
      title: Rene is now home
      message: Rene has arrived home, security has been disabled
      data:
        push:
          sound: "US-EN-Morgan-Freeman-Boyfriend-Is-Arriving.wav"

