alias: 'adaptive 4'

trigger:
  - platform: state
    entity_id: binary_sensor.hall_upstairs_sensor_occupancy
    from: 'off'
    to: 'on'
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/TV 1/set
      payload: '{"brightness":254,"color_temp":100}'
