alias: 'Bathroom movement'
trigger:
  - platform: state
    entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
    from: 'off'
    to: 'on'
action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.bathroom_last_movement
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.aeon_labs_zw100_multisensor_6_luminance
            below: '10'
        sequence:
          - type: turn_on
            device_id: switch.bathroom_lights
            entity_id: switch.bathroom_lights
            domain: switch
