alias: 'Bathroom no movement'
trigger:
  - platform: state
    entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
    from: 'on'
    to: 'off'
  - platform: numeric_state
    entity_id: sensor.aeon_labs_zw100_multisensor_6_relative_humidity
    below: '95'
condition:
  - condition: state
    entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.aeon_labs_zw100_multisensor_6_relative_humidity
    below: '95'
action:
  - type: turn_off
    device_id: switch.bathroom_lights
    entity_id: switch.bathroom_lights
    domain: switch
