alias: 'Bathroom update datetime movement'
trigger:
  - platform: state
    entity_id: sensor.aeon_labs_zw100_multisensor_6_sensor
    to: 'on'
action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.bathroom_last_movement
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

