alias: 'Garden timer on'
trigger:
  - platform: sun
    event: sunset
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Shed/set
      payload: '{"brightness":254,"color":{"x":0.612,"y":0.374},"color_temp":933}'
