alias: 'PC on'
trigger:
  - platform: state
    entity_id: binary_sensor.ping_pc
    from: 'off'
    to: 'on'
  - platform: sun
    event: sunset
condition:
  - condition: state
    entity_id: binary_sensor.ping_pc
    state: 'on'
  - condition: sun
    after: sunset
action:
  - brightness_pct: 50
    device_id: light.study_pc_1
    domain: light
    entity_id: light.study_pc_1
    type: turn_on
  - brightness_pct: 50
    device_id: light.study_pc_2
    domain: light
    entity_id: light.study_pc_2
    type: turn_on
