alias: 'PC off'
trigger:
  - platform: state
    entity_id: binary_sensor.ping_pc
    from: 'on'
    to: 'off'
action:
  - device_id: light.study_pc_1
    domain: light
    entity_id: light.study_pc_1
    type: turn_off
  - device_id: light.study_pc_2
    domain: light
    entity_id: light.study_pc_2
    type: turn_off
