alias: 'Attic no movement'
trigger:
  - platform: state
    entity_id: binary_sensor.attic_sensor_occupancy
    from: 'on'
    to: 'off'
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Attic/set/state
      payload: 'OFF'
